#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Interpreter version: python 2.7
#
# !!! DO NOT EDIT THIS FILE!!!
# !!! THIS IS AUTOMATICALLY GENERATED FILE !!!
# !!! SEE requests_template.py AND requests_generator.py FOR DETAILS !!!
#
# Imports =====================================================================
from collections import namedtuple


# Functions & classes =========================================================
class GenerateContract(namedtuple("GenerateContract", ["firma",
                                                       "pravni_forma",
                                                       "sidlo",
                                                       "ic",
                                                       "dic",
                                                       "zastoupen",
                                                       "jednajici"])):
    """
    Request to generate contract.

    Attributes:
        firma (str): As it is defined in contract.
        pravni_forma (str): As it is defined in contract.
        sidlo (str): As it is defined in contract.
        ic (str): As it is defined in contract.
        dic (str): As it is defined in contract.
        zastoupen (str): As it is defined in contract.
        jednajici (str): As it is defined in contract.
    """
    pass


#
# !!! DO NOT EDIT THIS FILE!!!
# !!! THIS IS AUTOMATICALLY GENERATED FILE !!!
# !!! SEE requests_template.py AND requests_generator.py FOR DETAILS !!!
#
class GenerateReview(namedtuple("GenerateReview", ['nazev',
                                                   'podnazev',
                                                   'cast',
                                                   'nazev_casti',
                                                   'isbn',
                                                   'isbn_souboru_publikaci',
                                                   'generated_isbn',
                                                   'author1',
                                                   'author2',
                                                   'author3',
                                                   'poradi_vydani',
                                                   'misto_vydani',
                                                   'rok_vydani',
                                                   'nakladatel_vydavatel',
                                                   'vydano_v_koedici_s',
                                                   'cena',
                                                   'offer_to_riv',
                                                   'category_for_riv',
                                                   'is_public',
                                                   'libraries_accessing',
                                                   'libraries_that_can_access',
                                                   'zpracovatel_zaznamu',
                                                   'url',
                                                   'format',
                                                   'filename'])):
    def __new__(self,
                nazev,
                podnazev,
                cast,
                nazev_casti,
                isbn,
                isbn_souboru_publikaci,
                generated_isbn,
                poradi_vydani,
                misto_vydani,
                rok_vydani,
                nakladatel_vydavatel,
                vydano_v_koedici_s,
                cena,
                offer_to_riv,
                category_for_riv,
                is_public,
                libraries_accessing,
                libraries_that_can_access,
                zpracovatel_zaznamu,
                url,
                format,
                filename,
                author1=None,
                author2=None,
                author3=None):
        return super(GenerateReview, self).__new__(
            self,
            nazev,
            podnazev,
            cast,
            nazev_casti,
            isbn,
            isbn_souboru_publikaci,
            generated_isbn,
            author1,
            author2,
            author3,
            poradi_vydani,
            misto_vydani,
            rok_vydani,
            nakladatel_vydavatel,
            vydano_v_koedici_s,
            cena,
            offer_to_riv,
            category_for_riv,
            is_public,
            libraries_accessing,
            libraries_that_can_access,
            zpracovatel_zaznamu,
            url,
            format,
            filename
        )

    def get_rst(self):
        rst = ""
        for key, val in REVIEW.items():
            val = val.strip()
            rst += ":%s: %s\n" % (key, val)

        return rst
#
# !!! DO NOT EDIT THIS FILE!!!
# !!! THIS IS AUTOMATICALLY GENERATED FILE !!!
# !!! SEE requests_template.py AND requests_generator.py FOR DETAILS !!!
#


class RST2PDF(namedtuple("RST2PDF", ["rst_content",
                                     "style",
                                     "header",
                                     "footer"])):
    """
    Generic request to convert RST file to PDF.

    Attributes:
        rst_content (str): Content of the generated PDF file.
        style (str): Style for the generated PDF file.
        header (str, default None): Header of each page.
        footer (str, default pagecount): Footer of each page.
    """
    def __new__(self, rst_content, style, header=None, footer=None):
        return super(RST2PDF, self).__new__(
            self,
            rst_content,
            style,
            header,
            footer
        )
